image: java:8
pipelines:
  default: # Pipelines that are triggered manually
      - step:
          script:
            - echo "--------- ECAM ---------"
 branches:  # Pipelines that run automatically on a commit to a branch
    azure:
      - step:
          caches:
            - gradle
          script:
            - echo "------- AZURE BUILD ----------"                       
            - echo $AWS_PW
            - echo $AWS_USER
            - bash ./gradlew build -x test 
      - step:
          name: Deploy to azure
          trigger: manual
          script:
            - bash ./azure.deploy.sh
            
