image: java:8
pipelines:
  default: # Pipelines that are triggered manually
      - step:
          script:
            - echo "--------- ECAM ---------"
  branches:  # Pipelines that run automatically on a commit to a branch
    azure:
      - step:
          caches:
            - gradle
          script:
            - echo "------- AZURE BUILD ----------"                       
            - bash ./gradlew build -x test 
      - step:
          name: Deploy to azure
          trigger: manual
          script:
            - curl -X POST -u $AZURE_USER:$AZURE_PW https://$AZURE_SITE.scm.azurewebsites.net/api/wardeploy --data-binary ./build/libs/ECAM.war
            
