USE `focus_test`;

DROP TABLE IF EXISTS `tbl_asset`;

CREATE TABLE `tbl_asset` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `modified_by` int(11) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL,
  `name` varchar(45) NOT NULL,
  `code` varchar(45) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `make` varchar(45) DEFAULT NULL,
  `model` varchar(100) DEFAULT NULL,
  `serial_no` varchar(100) DEFAULT NULL,
  `notes` varchar(300) DEFAULT NULL,
  `asset_category_id` int(11) DEFAULT NULL,
  `asset_status_id` int(11) DEFAULT NULL,
  `department_id` int(11) DEFAULT NULL,
  `asset_owner_id` int(11) DEFAULT NULL,
  `parent_asset_id` int(11) DEFAULT NULL,
  `warranty_id` int(11) DEFAULT NULL,
  `asset_event_id` int(11) DEFAULT NULL,
  `asset_offline_tracker_id` int(11) DEFAULT NULL,
  `is_online` tinyint(1) NOT NULL,
  `address` varchar(100) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `province` varchar(45) DEFAULT NULL,
  `postal_code` varchar(45) DEFAULT NULL,
  `country_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_asset_1` (`asset_category_id`) USING BTREE,
  KEY `fk_asset_2` (`asset_status_id`) USING BTREE,
  KEY `fk_asset_3` (`asset_owner_id`) USING BTREE,
  KEY `fk_asset_5` (`parent_asset_id`) USING BTREE,
  KEY `fk_asset_6` (`warranty_id`) USING BTREE,
  KEY `fk_asset_7` (`asset_event_id`) USING BTREE,
  KEY `fk_asset_8` (`asset_offline_tracker_id`) USING BTREE,
  CONSTRAINT `tbl_asset_ibfk_1` FOREIGN KEY (`asset_category_id`) REFERENCES `tbl_asset_catogery` (`id`),
  CONSTRAINT `tbl_asset_ibfk_2` FOREIGN KEY (`asset_status_id`) REFERENCES `tbl_asset_status` (`id`),
  CONSTRAINT `tbl_asset_ibfk_3` FOREIGN KEY (`asset_owner_id`) REFERENCES `tbl_asset_owner` (`id`),
  CONSTRAINT `tbl_asset_ibfk_4` FOREIGN KEY (`parent_asset_id`) REFERENCES `tbl_asset` (`id`),
  CONSTRAINT `tbl_asset_ibfk_5` FOREIGN KEY (`warranty_id`) REFERENCES `tbl_warranty` (`id`),
  CONSTRAINT `tbl_asset_ibfk_6` FOREIGN KEY (`asset_event_id`) REFERENCES `tbl_asset_event` (`id`),
  CONSTRAINT `tbl_asset_ibfk_7` FOREIGN KEY (`asset_offline_tracker_id`) REFERENCES `tbl_asset_offline_tracker` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;