USE `focus_test`;

DROP TABLE IF EXISTS `tbl_user`;

CREATE TABLE `tbl_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `api_user` tinyint(1) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `email_all_alert` tinyint(1) DEFAULT NULL,
  `full_name` varchar(200) DEFAULT NULL,
  `address` varchar(85) DEFAULT NULL,
  `image_path` varchar(200) DEFAULT NULL,
  `business_approve_date` datetime DEFAULT NULL,
  `business_approve_status` tinyint(1) DEFAULT NULL,
  `business_user_private_key` varchar(200) DEFAULT NULL,
  `currency_id` int(11) DEFAULT NULL,
  `acc_expiry_date` datetime DEFAULT NULL,
  `approval_expiry_date` datetime DEFAULT NULL,
  `request_date` datetime DEFAULT NULL,
  `default_login_location` varchar(200) DEFAULT NULL,
  `email_address` varchar(100) DEFAULT NULL,
  `email_all_msg` tinyint(1) DEFAULT NULL,
  `email_system_error` tinyint(1) DEFAULT NULL,
  `hourly_rate` decimal(10,0) DEFAULT NULL,
  `internal_mail_all_msg` tinyint(1) DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `notify_expire_days_before` int(11) DEFAULT NULL,
  `notify_on_DWOE` tinyint(1) DEFAULT NULL,
  `notify_on_DOAsset` tinyint(1) DEFAULT NULL,
  `notify_on_WOAssigned` tinyint(1) DEFAULT NULL,
  `notify_on_WOCompleted` tinyint(1) DEFAULT NULL,
  `notify_on_WODraft` tinyint(1) DEFAULT NULL,
  `notify_on_WOOnHold` tinyint(1) DEFAULT NULL,
  `notify_on_WOOpen` tinyint(1) DEFAULT NULL,
  `notify_on_WORequested` tinyint(1) DEFAULT NULL,
  `notify_on_WOWith_NoAsset` tinyint(1) DEFAULT NULL,
  `notfiy_on_WOwork_InProgress` tinyint(1) DEFAULT NULL,
  `personal_code` varchar(50) DEFAULT NULL,
  `send_mail_on_expire` tinyint(1) DEFAULT NULL,
  `sys_code` int(11) DEFAULT NULL,
  `system_level_user` tinyint(1) DEFAULT NULL,
  `telephone_1` varchar(15) DEFAULT NULL,
  `telephone_2` varchar(15) DEFAULT NULL,
  `user_approve_date` datetime DEFAULT NULL,
  `user_approve_status` int(11) DEFAULT NULL,
  `user_status` int(11) DEFAULT NULL,
  `user_title` varchar(10) DEFAULT NULL,
  `welcome_email_sent` tinyint(1) DEFAULT NULL,
  `version` int(11) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by` int(11) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;